language: java
install: true

jdk:
  - openjdk8

stages:
  - analyze
  - test
  - release

jobs:
  include:
    - stage: analyze
      name: "Analyze production code using PMD"
      script: ./gradlew clean pmdMain

    - stage: analyze
      name: "Analyze production code using Findbugs"
      script: ./gradlew clean findbugsMain

    - stage: analyze
      name: "Analyze code style using checkstyle"
      script: ./gradlew clean checkstyleMain checkstyleTest

    - stage: test
      name: "Execute unit test"
      script:
        - ./gradlew clean test
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      name: "Release to Maven Central Repository"
      if: tag =~ ^v
      script:
        - ./prepare_before_publish
        - ./gradlew commandbus-spec:publish
        - ./gradlew commandbus-core:publish
        - ./gradlew commandbus-basic-middleware:publish
        - ./gradlew commandbus-core-full:publish
        - ./gradlew commandbus-spring:publish
        - ./gradlew commandbus-spring-full:publish
        - ./cleanup_after_publish

    - stage: release
      name: "Publish snapshot"
      if: branch =~ ^(develop|hotfix|release).*
      script:
        - ./prepare_before_publish
        - ./gradlew commandbus-spec:publish -PSNAPSHOT=true
        - ./gradlew commandbus-core:publish -PSNAPSHOT=true
        - ./gradlew commandbus-basic-middleware:publish -PSNAPSHOT=true
        - ./gradlew commandbus-core-full:publish -PSNAPSHOT=true
        - ./gradlew commandbus-spring:publish -PSNAPSHOT=true
        - ./gradlew commandbus-spring-full:publish -PSNAPSHOT=true
        - ./cleanup_after_publish