language: java
install: true

jdk:
  - oraclejdk8

stages:
  - analyze
  - test
  - publish

jobs:
  include:
    - stage: analyze
      name: "Analyze production code using PMD"
      script: ./gradlew clean pmdMain

    - stage: analyze
      name: "Analyze production code using Findbugs"
      script: ./gradlew clean findbugsMain

    - stage: analyze
      name: "Analyze code style using checkstyle"
      script: ./gradlew clean checkstyleMain checkstyleTest

    - stage: test
      name: "Execute unit test"
      script:
        - ./gradlew clean test
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)

    - stage: publish
      name: "Publish to Maven Central Repository"
      branches:
        only:
          - master
      script:
        - ./prepare_before_publish
        - ./gradlew publish

after_script:
  - ./clean_after_publish